### ISSUE TITLE
Kodoma Trinus/fanowin f1 usng Marlin

### ISSUE THREAD

**Issue by watchofficer** [Voxel8/Marlin#168]
I've got a Fanowin F1 3d printer with the original control board. I would like to know if anyone knows which board codes/name could be used in marlin to operate the original board.

It used the original Pango software with the CH341

I've already received the MKS GEN V1.4 , to replace the origianl Fanowin control board, but I am curious to know if the original works.

**Comment by maxvoxel8** [comment]
This is a fork of the original Marlin repo, please post this issue in https://github.com/MarlinFirmware/Marlin.
