### ISSUE TITLE
Changes to thermistor error behaviors

### ISSUE THREAD

**Issue by Mikenanotube** [Voxel8/Marlin#18]
Max temp and min temp hit behaviors turn off the thermoplastic extruder and prevent the printer from receiving new commands, but they should also send the command to turn off pressure-based extrusion, and maybe even turn off the motors, since it may be useful to move the print engine around.

The issue is especially bad with the new printers, where the cartridge can be lifted off the pogo pins if the print engine slams into the print bed, disconnecting the thermistor. Then with the motors on it is impossible to change the Z height and put the cartridge back in to continue printing - and if you restart things it will just send another min temp or max temp error immediately.

**Comment by kdumontnu** [comment]
Merge with Issue #17
