### ISSUE TITLE
Z_DUAL_ENDSTOPS defined in Configuration_adv.h

### ISSUE THREAD

**Issue by kdumontnu** [Voxel8/Marlin#22]
Why is Z_DUAL_ENDSTOPS defined in Configuration_adv.h?

Is this a valid parameter?

**Comment by kdumontnu** [comment]
@riningerr @jminardi ^

**Comment by jminardi** [comment]
It is wrapped in an #ifdef: https://github.com/Voxel8/Marlin/blob/Integration/Marlin/Configuration_adv.h#L128

which is not defined, so `Z_DUAL_ENDSTOPS` is not defined.
