### ISSUE TITLE
G29 does not home correctly

### ISSUE THREAD

**Issue by rebeccavoxel8** [Voxel8/Marlin#25]
When calling G29 from a random position on the printer (after running G28), G29 will ram the gantry into the front of the printer, without respect for endstops
sad.

**Comment by jminardi** [comment]
See this issue upstream: https://github.com/MarlinFirmware/MarlinDev/issues/126#issuecomment-137378853

**Comment by kevingelion** [comment]
thanks @kdumontnu :octopus:
