### ISSUE TITLE
Set z probe offset higher

### ISSUE THREAD

**Issue by jminardi** [Voxel8/Marlin#31]
One mm is not enough for some of our more extreme unleveled beds

**Comment by kdumontnu** [comment]
@kevingelion is this issue resolved?

**Comment by jminardi** [comment]
Yes this is done

On Monday, October 12, 2015, Kyle D. <notifications@github.com> wrote:

> @kevingelion <https://github.com/kevingelion> is this issue resolved?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Voxel8/Marlin/issues/31#issuecomment-147482661>.
>


-- 
Jack Minardi
jack.minardi.org
jack@minardi.org

**Comment by kevingelion** [comment]
Yep, I belive @jminardi fixed this
