### ISSUE TITLE
[Build Script] Fans don't work after uploading with build script

### ISSUE THREAD

**Issue by jminardi** [Voxel8/Marlin#58]
Only tested on my mac. This means that the rambo board is not properly selected.

**Comment by kevingelion** [comment]
Didn't we test this before on Mac without issues?

**Comment by lewisgroup** [comment]
I thought we did but either we didn't confirm the fans worked or something
changes in the meantime.

On Mon, Oct 19, 2015 at 10:57 AM, Kevin Murphy <notifications@github.com>
wrote:

> Didn't we test this before on Mac without issues?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Voxel8/Marlin/issues/58#issuecomment-149239847>.
>



-- 
Jack Minardi
jack.minardi.org
jack@minardi.org

**Comment by kevingelion** [comment]
Which branch were you on?

**Comment by jminardi** [comment]
Master

**Comment by pizzyflavin** [comment]
Isn't this resolved with the correct pins file?

**Comment by kevingelion** [comment]
yes
