### ISSUE TITLE
Marlin doesn't build with #define pneumatics disabled

### ISSUE THREAD

**Issue by kdumontnu** [Voxel8/Marlin#82]
":#error TEMP_SENSOR_1 is required with 2 or more EXTRUDERS"

**Comment by kdumontnu** [comment]
@pizzyflavin is this a legitimate issue? I feel like we need to be able to disable this for some debug applications

**Comment by pizzyflavin** [comment]
@kdumontnu this is a legit issue.

I agree, we should be able to do this. When the feature was originally
developed, it was assumed that there was always a silver cartridge (we
didn't do modular/removable cartridges yet).

**Comment by danthompson41** [comment]
Made it so this shouldn't have to be disabled?
