### ISSUE TITLE
I2C Timeout

### ISSUE THREAD

**Issue by kdumontnu** [Voxel8/Marlin#89]
Marlin should have a way to handle I2C time-out when the communication in interfered with. This was causing the printer to hang in an infinite loop when we had the stepper motor cross-talk issue with a previous printer.

**Comment by danthompson41** [comment]
This is implemented via a change to the arduino libraries. If compiled on a computer with the change, this will be implemented. Working with jack to get this implemented through octoprint's updates, via giving the pi a hex file rather than it pulling from the source code
